[package]
name = "av-ontology"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rdf-model.workspace = true
rdf-io.workspace = true
anyhow.workspace = true
